"use client";

import { ArrowRight, CalendarDays, ChevronRight, Clock3, Compass, ExternalLink, MapPin, Search, Sparkles, Users } from "lucide-react";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type View = "events" | "communities";

const communities = [{ id: "community-placeholder", name: "Campus communities", type: "Community directory", description: "Student associations, faith communities, academic groups, creative communities and clubs will appear here as FUTAGO verifies their details.", location: "Across FUTA" }];

export default function DiscoverPage() {
  const router = useRouter();
  const [view, setView] = useState<View>("events");
  const [query, setQuery] = useState("");
  const filteredCommunities = useMemo(() => { const q = query.trim().toLowerCase(); return communities.filter((c) => !q || `${c.name} ${c.type} ${c.description} ${c.location}`.toLowerCase().includes(q)); }, [query]);

  return (
    <main className="min-h-[100dvh] overflow-x-hidden bg-[#f4f3ed] pb-32 text-[#102017] dark:bg-[#061009] dark:text-white">
      <div className="mx-auto w-full max-w-[1120px] px-4 pb-8 pt-5 sm:px-6 md:px-8 lg:px-10">
        <header className="flex items-center justify-between gap-4"><div><div className="inline-flex items-center gap-2 text-xs font-extrabold uppercase tracking-[0.14em] text-[#397151] dark:text-[#8ce6ad]"><Compass size={15}/> Discover FUTA</div><h1 className="mt-2 text-[36px] font-black leading-none tracking-[-0.055em] sm:text-[48px]">What&apos;s happening,<span className="block text-[#34744c] dark:text-[#8ce6ad]">around campus.</span></h1></div><div className="hidden h-12 w-12 items-center justify-center rounded-[17px] bg-[#153f2a] text-[#9bedb7] sm:flex"><Sparkles size={21}/></div></header>
        <p className="mt-4 max-w-[650px] text-sm leading-6 text-black/48 dark:text-white/42">Keep up with campus events, what&apos;s happening now and communities worth knowing. Places and everyday campus services stay in Explore.</p>

        <div className="mt-6 inline-flex rounded-[18px] border border-black/[0.055] bg-white/70 p-1.5 dark:border-white/[0.07] dark:bg-white/[0.035]">
          {(["events","communities"] as View[]).map((item) => <button key={item} type="button" onClick={() => setView(item)} className={`min-h-11 touch-manipulation rounded-[13px] px-5 text-sm font-extrabold capitalize transition ${view === item ? "bg-[#153f2a] text-white dark:bg-[#8ce6ad] dark:text-[#092417]" : "text-black/42 dark:text-white/42"}`}>{item}</button>)}
        </div>

        {view === "events" ? <>
          <section className="mt-6 overflow-hidden rounded-[30px] bg-[#123f29] p-5 text-white shadow-[0_24px_70px_rgba(18,63,41,0.16)] sm:p-7"><div className="inline-flex items-center gap-2 rounded-full bg-white/[0.07] px-3 py-1.5 text-[11px] font-bold uppercase tracking-[0.12em] text-[#a9efc1]"><span className="h-2 w-2 animate-pulse rounded-full bg-[#9bedb7]"/> Campus pulse</div><h2 className="mt-4 max-w-[560px] text-[28px] font-black leading-[1.02] tracking-[-0.045em] sm:text-[36px]">Don&apos;t miss what&apos;s happening at FUTA.</h2><p className="mt-3 max-w-[600px] text-sm leading-6 text-white/55">Upcoming and live events belong here. FUTAGO will only publish dates, venues and organisers when the information can be verified.</p><a href="#upcoming" className="mt-5 inline-flex min-h-12 items-center gap-2 rounded-[16px] bg-[#9bedb7] px-5 text-sm font-extrabold text-[#0b2b1b]">See upcoming <ArrowRight size={17}/></a></section>

          <section className="mt-6 grid gap-4 md:grid-cols-2">
            <article className="rounded-[26px] border border-[#2e7048]/15 bg-[#e8f0e7] p-5 dark:border-[#8ce6ad]/10 dark:bg-[#102318]"><div className="flex items-start gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-[15px] bg-white/80 text-[#34744c] dark:bg-white/[0.07] dark:text-[#8ce6ad]"><Clock3 size={20}/></div><div><p className="text-[11px] font-black uppercase tracking-[0.12em] text-[#397151] dark:text-[#8ce6ad]">Happening now</p><h2 className="mt-2 text-lg font-black">No verified live event right now</h2><p className="mt-2 text-sm leading-6 text-black/45 dark:text-white/40">When an approved campus event is currently running, FUTAGO will show its venue, time and directions here.</p></div></div></article>
            <article className="rounded-[26px] border border-black/[0.055] bg-white/70 p-5 dark:border-white/[0.07] dark:bg-white/[0.035]"><div className="flex items-start gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-[15px] bg-[#eee9dc] text-[#7b6424] dark:bg-[#e0c563]/10 dark:text-[#e0c563]"><CalendarDays size={20}/></div><div><p className="text-[11px] font-black uppercase tracking-[0.12em] text-black/35 dark:text-white/35">This week</p><h2 className="mt-2 text-lg font-black">Your weekly campus view</h2><p className="mt-2 text-sm leading-6 text-black/45 dark:text-white/40">Verified events happening during the current week will be grouped here.</p></div></div></article>
          </section>

          <section id="upcoming" className="mt-7"><p className="text-xs font-extrabold uppercase tracking-[0.13em] text-[#397151] dark:text-[#8ce6ad]">Coming up</p><h2 className="mt-1 text-xl font-black">Upcoming events</h2><article className="mt-4 rounded-[28px] bg-[#173f2b] p-5 text-white sm:p-6"><div className="flex h-11 w-11 items-center justify-center rounded-[15px] bg-white/[0.08] text-[#9bedb7]"><CalendarDays size={20}/></div><h3 className="mt-5 text-[25px] font-black tracking-[-0.04em]">Events will appear here once approved</h3><p className="mt-3 max-w-[650px] text-sm leading-6 text-white/58">The event system will store title, start and end time, venue, organiser, description and verification state. That keeps Discover current instead of showing guessed or stale information.</p><div className="mt-5 flex flex-wrap gap-2 text-[11px] font-bold text-white/55"><span className="rounded-full bg-white/[0.07] px-3 py-2">Date & time</span><span className="rounded-full bg-white/[0.07] px-3 py-2">Venue</span><span className="rounded-full bg-white/[0.07] px-3 py-2">Organiser</span></div></article></section>

          <section className="mt-5 rounded-[24px] border border-black/[0.05] bg-white/65 p-5 dark:border-white/[0.06] dark:bg-white/[0.03]"><p className="text-xs font-extrabold uppercase tracking-[0.11em] text-[#397151] dark:text-[#8ce6ad]">Official updates</p><p className="mt-2 text-sm leading-6 text-black/45 dark:text-white/40">When an event has an official FUTA source, FUTAGO can link students back to it.</p><a href="https://futa.edu.ng/" target="_blank" rel="noreferrer" className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-[15px] bg-[#153f2a] px-4 text-sm font-extrabold text-white dark:bg-[#8ce6ad] dark:text-[#092417]">Official FUTA site <ExternalLink size={15}/></a></section>
        </> : <section className="mt-6"><div className="rounded-[28px] bg-[#173f2b] p-5 text-white sm:p-6"><Users size={22} className="text-[#9bedb7]"/><h2 className="mt-5 text-[27px] font-black">Find your people.</h2><p className="mt-2 max-w-[620px] text-sm leading-6 text-white/55">Discover verified student associations, faith communities, academic groups, creative communities, clubs and other student-led groups around FUTA.</p></div><div className="mt-5 flex min-h-[58px] items-center gap-3 rounded-[20px] border border-black/[0.055] bg-white/80 px-4 dark:border-white/[0.07] dark:bg-white/[0.045]"><Search size={18} className="text-black/35 dark:text-white/35"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search communities..." className="min-w-0 flex-1 bg-transparent text-base outline-none"/></div><div className="mt-5 grid gap-3 md:grid-cols-2">{filteredCommunities.map((c)=><article key={c.id} className="rounded-[26px] border border-black/[0.05] bg-white/70 p-5 dark:border-white/[0.07] dark:bg-white/[0.035]"><div className="flex h-11 w-11 items-center justify-center rounded-[15px] bg-[#edf5ee] text-[#34744c] dark:bg-[#8ce6ad]/10 dark:text-[#8ce6ad]"><Users size={19}/></div><h3 className="mt-5 text-lg font-black">{c.name}</h3><p className="mt-2 text-sm leading-6 text-black/45 dark:text-white/40">{c.description}</p><div className="mt-5 flex items-center gap-1.5 text-xs font-semibold text-black/35 dark:text-white/30"><MapPin size={14}/> {c.location}</div></article>)}</div></section>}

        <button type="button" onClick={() => router.push("/explore")} className="mt-7 flex min-h-[92px] w-full items-center justify-between gap-5 rounded-[24px] border border-black/[0.055] bg-white/60 p-5 text-left dark:border-white/[0.06] dark:bg-white/[0.025]"><div><p className="text-xs font-extrabold uppercase tracking-[0.11em] text-[#397151] dark:text-[#8ce6ad]">Looking for a place?</p><p className="mt-1 text-sm font-bold text-black/55 dark:text-white/50">Food, study spots, services and campus locations are in Explore.</p></div><ChevronRight size={20}/></button>
      </div>
    </main>
  );
}
